version: "2"
run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly
issues:
  max-same-issues: 0

linters:
  default: none
  enable:
    - gosec
    - goconst
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    goconst:
      min-len: 4 # ignore "gcp" and "aws"

formatters:
  enable:
    - gofmt
