dist: /tmp/dist
builds:
  - main: cmd/aus/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X gitlab.cee.redhat.com/service/aus-cli/cmd/aus/version.Version={{.Version}}
      - -X gitlab.cee.redhat.com/service/aus-cli/cmd/aus/version.Commit={{.Commit}}
    ignore:
      - goos: linux
        goarch: "386"
archives:
  - format: binary
    name_template: >-
      aus_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
